services:
  facialrec:
    build: .
    environment:
      - OPENCV_FFMPEG_CAPTURE_OPTIONS=rtsp_transport;tcp
    volumes:
      - ./config:/app/config
      - ./db:/app/db
      - ./weights:/root/.deepface/weights
    # Use CDI devices instead of `gpus: all` to avoid legacy hook
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi 
              device_ids:
                - "nvidia.com/gpu=all"
              capabilities: ["gpu"]
    restart: unless-stopped
